//
// Created by alexis on 23/01/18.
//

#ifndef NOMAD_SOFTWARE_CENTER_REMOVEAPPIMAGEINTERACTOR_H
#define NOMAD_SOFTWARE_CENTER_REMOVEAPPIMAGEINTERACTOR_H



class RemoveAppImageInteractor {

};



#endif //NOMAD_SOFTWARE_CENTER_REMOVEAPPIMAGEINTERACTOR_H
