name: Nitrux Software Center Deb

on:
  workflow_dispatch:
    inputs:
      packageCloudRepo:
        description: 'Package Cloud Repo'
        required: true
        default: 'testing'
        type: choice
        options:
        - testing
      packageVersion:
        description: 'Package Version'
        required: true
        type: string

jobs:
  build-deb:
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:noble
      env:
        DEBIAN_FRONTEND: noninteractive
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

    steps:
      - name: Install basic packages
        run: apt-get update -q && apt-get -qy install sudo && apt-get -qy install curl wget gnupg python3-pip patchelf build-essential ruby-full

      - name: Install package cloud
        run: gem install package_cloud

      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: ./scripts/install-build-deps.sh

      - name: Generate deb
        run: ./scripts/build-deb.sh
        env:
          PACKAGE_VERSION: ${{ inputs.packageVersion }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ./build/*.deb
          retention-days: 1
      
      - name: Upload package to Package Cloud
        run: package_cloud push nitrux/${{ inputs.packageCloudRepo }}/debian/trixie ./build/*.deb